---
- name: 分发calico.yaml
  template:
    src: calico.yaml.j2
    dest: /opt/kubernetes/cfg/calico.yaml
  when:
    - role == 'master'

- name: 安装网络插件
  raw: kubectl apply -f /opt/kubernetes/cfg/calico.yaml
  when:
    - role == 'master'
