---
- name: 分发相关配置的yaml文件
  template:
    src: tls-instructs-csr.yaml.j2
    dest: /opt/kubernetes/cfg/tls-instructs-csr.yaml

- name: 配置自动授权
  command: "{{ item }}"
  with_items:
    - kubectl apply -f /opt/kubernetes/cfg/tls-instructs-csr.yaml
    - kubectl create clusterrolebinding node-client-auto-approve-csr --clusterrole=system:certificates.k8s.io:certificatesigningrequests:nodeclient --user=kubelet-bootstrap
    - kubectl create clusterrolebinding node-client-auto-renew-crt --clusterrole=system:certificates.k8s.io:certificatesigningrequests:selfnodeclient --group=system:nodes
    - kubectl create clusterrolebinding node-server-auto-renew-crt --clusterrole=system:certificates.k8s.io:certificatesigningrequests:selfnodeserver --group=system:nodes
    - kubectl create clusterrolebinding kubernetes --clusterrole=cluster-admin --user=kubernetes
    - kubectl create clusterrolebinding kubelet-bootstrap --clusterrole=system:node-bootstrapper --user=kubelet-bootstrap
  args:
    chdir: /opt/kubernetes/bin/
  when:
    - role == 'master'
